### ISSUE TITLE
Reconcile mismatch of Shijing node numbers by calculating them from PoePy

### ISSUE THREAD

**Issue by nh36** [hanproj/hanproject#9]

**Comment by LinguList** [comment]
Node numbers, what is the problem here?

**Comment by ashhenson** [comment]
Hey Mattis,
Nice to (virtually) meet you! My name is Ash and I work on the hanproject.
Basically, what this issue is about is that I wrote code to try and
recreate what you
did in your 2017 paper. The number of nodes I came up with (1809) was
different than the number you list in the paper (1845). Later, I looked at
the results of
my code vs. results from poepy. Both came up to 1809, but actually, they
weren't the exact same 1809. They were off by 3 nodes or so, and I figured
out
where the difference came from for 2 of those nodes. The last one I just
left in the interest of time, since it probably didn't represent a
fundamental misunderstanding
on my part of what you were doing in the 2017 paper. I'll be using poepy
going forward. I just did this whole thing as an experiment to better
understand your work
in specific, and applying Network theory to rhymes in general.

Ash

**Comment by LinguList** [comment]
Hi Ash, nice to meet you too! There is a problem with PoePy in so far as I need to do a thorough check of the code base. So if you use PoePy for these experiments, may I ask you to share the code with me, so I double-check and make sure to also fix bugs from poepy for this purpose? Cases like the one you mention here deserve investigation my side, as they should actually not turn up, and if there are errors in the code underlying older papers, we need to address them and fix them.

Did you use the exact data and compare with the workflow that was published for the 2017 paper, or did you use a new version of Baxter's 1992 data? This may also lead to discrepancies.

**Comment by LinguList** [comment]
I just also gave you write access to poepy. So we can work on this together, and you'd of course be listed as an author, if new ideas come up, if we learn about bugs, and decide to make the code base better tested and userfriendly.

**Comment by ashhenson** [comment]
Hey Mattis,
Yeah, that sounds great! I didn't find any errors in Poepy per se. I could
go back and look at the 3 different chars (for the Nodes) sometime next
week and report the differences here (it's also
likely that it's my code that has the issue). One thing in regards to the
calculation of edges is that Poepy produces a lot (in the case of the
entire Shijing, 300 something) cases
where it reports an edge with the same character on both sides of the edge.
I looked at the Shijing data (btw, I'm using your Baxter1992.tsv file to
answer your earlier question)
for those cases, and in some cases couldn't find a rhyme, though I figured
it may have something to do with the "potential" rhymes mentioned in the
2017 paper (also, I've
been working off of the 2016 pre-published version, so some of the issue --
as far as node numbers, etc., --  may be there if the two papers aren't
exactly the same). I can also
send you those pairs of self-rhyming characters sometime. Thanks for the
prompt response!

Ash

**Comment by LinguList** [comment]
For starters, if you send me the exact baxter file you use and your 
code, I'd have a look next week, when I find time.

I'd then also check my code from 2017, which is in fact something 
outdated that should be re-done, also since I introduce a new way to 
measure rhymes now, which only considers adjacent rhymes, which I think 
is much better and should be the new standard, an idea introduced to me 
by Aison Bu, although I do not know if this was exactly what Aison meant 
(see here: 
http://phylonetworks.blogspot.com/2020/08/constructing-rhyme-networks-from-rhymes.html).

So my suggestion would be to include this new code into PoePy and to 
make a checking of the self-nodes, which is obviously an error, although 
in a consecutive-rhyme-model you would have the possibility that an 
identical word IS used as a rhyme, although not considered as a 
stylistic master-piece.

**Comment by LinguList** [comment]
Okay, attaching does not work with sending data to github, so I have not received the file. But the problems we face here tell me that we are running into different-file issues, not necessarily different-code issues. 

What we need to do now is to make a unique fixed format for Baxter 1992 (which I should do) in the best version we can get. We can then update any errors we find there, and from THERE we can test if our codes handle things badly.

**Comment by ashhenson** [comment]
Hey Mattis,
Yeah, I attached the file to the email in order to keep it out of the git
repo. Having two versions of the same data file in the repo would not be
good.
But, I wanted you to have a copy of that file so you could test with it. I
think having one unified version of the file as you suggest is the best
solution.
The only change I made to the file was for Ode 63.9, line 6, I changed 'b'
to 'a' to match Baxter 1992.
Just let me know when you have a unified version of the file and I'll
re-run everything.

Ash

**Comment by ashhenson** [comment]
Hey Mattis,
At Nathan's request, I'm going to close this issue, but open up another one
with a more appropriate name (since the number of nodes issue has been
resolved).
It'll be called "Troubleshooting discrepancies between PoePy and Ash's
code" (if there is a name you would prefer over this one, just let me know).

Ash

**Comment by ashhenson** [comment]
Closing this issue since the number of nodes has been resolved. Will open another issue called "Troubleshooting discrepancies between PoePy and Ash's code" to continue the discussion of the edges.

**Comment by ashhenson** [comment]
Hey Mattis,
Sorry, I may have misunderstood your email. Are you saying you weren't able
to get the file because this email is going through GitHub?
If that's the case, can you give me another email address to email it to.
Or any other way I can get the data to you besides adding the
file to the repo.

Thanks,
Ash

**Comment by LinguList** [comment]
You have my emails from email conversation, right? Otherwise it is also online.
